In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

arr3 = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
arr1.shape

(3,)

In [8]:
arr2.shape

(2, 3)

In [9]:
arr3.shape

(2, 3, 3)

In [10]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [11]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
arr1.size, arr2.size, arr3.size

(3, 6, 18)

In [13]:
type(arr1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5