In [1]:
import numpy as np

## 1. DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

arr3 = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
arr1.shape

(3,)

In [8]:
arr2.shape

(2, 3)

In [9]:
arr3.shape

(2, 3, 3)

In [10]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [11]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
arr1.size, arr2.size, arr3.size

(3, 6, 18)

In [13]:
type(arr1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 6, 5, 9, 1],
       [7, 4, 7, 4, 2],
       [7, 1, 5, 1, 8]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.33278828, 0.54515511, 0.17971645],
       [0.32315696, 0.14945671, 0.72499494],
       [0.89527028, 0.95998619, 0.11975093],
       [0.9834114 , 0.69114579, 0.48823904],
       [0.9495295 , 0.89111525, 0.51425079]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.58337704, 0.05105692, 0.99316887],
       [0.59234822, 0.2189358 , 0.84650416],
       [0.63375137, 0.88475511, 0.43476328],
       [0.23272776, 0.63840776, 0.54751288],
       [0.96290194, 0.66655856, 0.67543024]])

In [36]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing Arrays and Martices

In [41]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr1

array([1, 2, 3])

In [44]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
arr1[0]

1

In [47]:
arr2[0]

array([1. , 2. , 3.3])

In [48]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
arr4 = np.random.randint(10, size=(2, 3, 4, 5))
arr4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [51]:
arr4.shape, arr4.ndim

((2, 3, 4, 5), 4)

In [75]:
# Get the first four numbers of the inner most arrays
arr4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating and Comparing Arrays

### Arithmetic

In [76]:
arr1

array([1, 2, 3])

In [77]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [78]:
arr1 + ones

array([2., 3., 4.])

In [79]:
arr1 - ones

array([0., 1., 2.])

In [80]:
arr1 * ones

array([1., 2., 3.])

In [81]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [82]:
arr1 * arr2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [88]:
arr1 / ones

array([1., 2., 3.])

In [89]:
arr2 / arr1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [90]:
# Floor division removes the decimals (rounds down)
arr2 // arr1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [91]:
arr2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [92]:
np.square(arr2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [93]:
np.add(arr1, ones)

array([2., 3., 4.])

In [94]:
arr1 % 2

array([1, 0, 1], dtype=int32)

In [95]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [96]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])