In [1]:
import numpy as np

## 1. DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

arr3 = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
arr1.shape

(3,)

In [8]:
arr2.shape

(2, 3)

In [9]:
arr3.shape

(2, 3, 3)

In [10]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [11]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
arr1.size, arr2.size, arr3.size

(3, 6, 18)

In [13]:
type(arr1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 4, 6, 5, 7],
       [8, 3, 1, 4, 3],
       [7, 6, 6, 0, 4]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.46144214, 0.87755491, 0.96434713],
       [0.93735065, 0.2407029 , 0.65903112],
       [0.91504818, 0.23734586, 0.2718827 ],
       [0.71186276, 0.28690946, 0.7509095 ],
       [0.55246396, 0.45510987, 0.99158645]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.78636286, 0.06300285, 0.27855605],
       [0.68873819, 0.7159437 , 0.26991861],
       [0.16691815, 0.88150049, 0.6131807 ],
       [0.14467714, 0.15955457, 0.17606214],
       [0.49116976, 0.34268305, 0.95951594]])